#!/usr/bin/env python3
"""Regenerate aws/Types.dhall and aws/Services.dhall from the upstream awsdac
icon-definition YAML.

Usage:
    python3 tools/gen-aws-types.py

Writes aws/Types.dhall and aws/Services.dhall in place. Re-run when upstream
adds new resources.
"""
from __future__ import annotations

import re
import sys
import urllib.request
from collections import defaultdict
from pathlib import Path

URL = (
    "https://raw.githubusercontent.com/awslabs/diagram-as-code/"
    "main/definitions/definition-for-aws-icons-light.yaml"
)

# AWS::Diagram::* types that awsdac handles directly in code rather than via
# the YAML definition file (see internal/ctl/create.go).
SPECIAL_DIAGRAM = ["Canvas", "Resource", "VerticalStack", "HorizontalStack"]

TYPE_LINE = re.compile(r'^\s+"?(AWS::[^"]+?)"?:\s*$')

REPO_ROOT = Path(__file__).resolve().parent.parent


def fetch_yaml() -> str:
    with urllib.request.urlopen(URL) as resp:
        return resp.read().decode()


def extract_types(yaml_text: str) -> list[str]:
    found = set()
    for line in yaml_text.splitlines():
        m = TYPE_LINE.match(line)
        if m:
            found.add(m.group(1))
    return sorted(found)


def is_dhall_ident(name: str) -> bool:
    # Conservative: letters/digits/underscore, not starting with a digit.
    return bool(re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name))


def group_types(types: list[str]) -> tuple[list[tuple[str, str]], dict[str, list[tuple[str, str]]]]:
    services: list[tuple[str, str]] = []   # (Key, full "AWS::Key")
    resources: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for t in types:
        parts = t.split("::")
        if len(parts) == 2:
            svc = parts[1]
            if not is_dhall_ident(svc):
                continue
            services.append((svc, t))
        elif len(parts) == 3:
            _, svc, res = parts
            if not is_dhall_ident(svc) or not is_dhall_ident(res):
                continue
            resources[svc].append((res, t))
    for svc in resources:
        resources[svc].sort()
    return services, resources


def add_special_diagram(resources: dict[str, list[tuple[str, str]]]) -> None:
    existing = {res for res, _ in resources["Diagram"]}
    for s in SPECIAL_DIAGRAM:
        if s not in existing:
            resources["Diagram"].append((s, f"AWS::Diagram::{s}"))
    resources["Diagram"].sort()


def render_subrecord(rows: list[tuple[str, str]], indent: str) -> list[str]:
    if not rows:
        return [f"{indent}{{=}}"]
    out = [f"{indent}{{ {rows[0][0]} = \"{rows[0][1]}\""]
    for key, value in rows[1:]:
        out.append(f"{indent}, {key} = \"{value}\"")
    out.append(f"{indent}}}")
    return out


def render_types(resources: dict[str, list[tuple[str, str]]]) -> str:
    out = [
        "-- Generated by tools/gen-aws-types.py from the upstream awsdac",
        "-- icon-definition YAML. Do not edit by hand; re-run the generator.",
    ]
    services = sorted(resources)
    for i, svc in enumerate(services):
        sep = "{ " if i == 0 else ", "
        sub = render_subrecord(resources[svc], indent="  ")
        # First sub-record line starts with "  { ..." — splice the leading
        # "ServiceName =" onto a line of its own for readability.
        out.append(f"{sep}{svc} =")
        out.extend(sub)
    out.append("}")
    return "\n".join(out) + "\n"


def render_services(services: list[tuple[str, str]]) -> str:
    out = [
        "-- Generated by tools/gen-aws-types.py from the upstream awsdac",
        "-- icon-definition YAML. Do not edit by hand; re-run the generator.",
        "--",
        "-- Service-level type names (the 2-segment AWS::Foo form). awsdac",
        "-- falls back to these icons when a 3-segment resource type isn't",
        "-- defined; they're also useful when you want a plain service icon.",
    ]
    out.extend(render_subrecord(services, indent=""))
    return "\n".join(out) + "\n"


def main() -> int:
    print(f"Fetching {URL}", file=sys.stderr)
    text = fetch_yaml()
    types = extract_types(text)
    print(f"  found {len(types)} AWS:: keys", file=sys.stderr)

    services, resources = group_types(types)
    add_special_diagram(resources)

    types_dhall = render_types(resources)
    services_dhall = render_services(services)

    (REPO_ROOT / "aws" / "Types.dhall").write_text(types_dhall)
    (REPO_ROOT / "aws" / "Services.dhall").write_text(services_dhall)

    total_resources = sum(len(v) for v in resources.values())
    print(
        f"Wrote aws/Types.dhall ({len(resources)} services, "
        f"{total_resources} resources) and aws/Services.dhall "
        f"({len(services)} services).",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
